/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ARCH_X86 1

#define ARCH_X86_64 1

#define BINDIR "bin"

#define BUG_REPORT_URL "https://gitlab.gnome.org/GNOME/gimp/issues/new"

#define CC "clang"

#define CC_VERSION "clang version 20.1.7\nTarget: x86_64-w64-windows-gnu\nThread model: posix\nInstalledDir: C:/msys64/clang64/bin\n"

#define CHECK_UPDATE

#define COLOR_PROFILE_DIRECTORY "/usr/share/color/icc"

#define COMPILE_SSE2_INTRINISICS 1

#define COMPILE_SSE4_1_INTRINISICS 1

#define DATAROOTDIR "share"

#define DESKTOP_DATADIR "share"

#define ENABLE_MP 1

#define ENABLE_NLS

#define ENABLE_RELOCATABLE_RESOURCES 1

#undef ENABLE_WIN32_DEBUG_CONSOLE

#define EXEC_PREFIX ""

#define GETTEXT_PACKAGE "gimp30"

#define GIMPDATADIR "share/gimp/3.0"

#define GIMPDIR "GIMP"

#define GIMPPLUGINDIR "lib/gimp/3.0"

#define GIMPSYSCONFDIR "etc/gimp/3.0"

#define GIMP_APP_VERSION "3.0"

#define GIMP_APP_VERSION_STRING "3.0"

#define GIMP_BUILD_ID "org.gimp.GIMP_official"

#define GIMP_BUILD_PLATFORM "windows"

#define GIMP_BUILD_PLATFORM_FAMILY "windows"

#define GIMP_COMMAND "gimp-3.0"

#define GIMP_DATA_VERSION "3.0"

#define GIMP_DESKTOP_NAME "gimp"

#undef GIMP_IS_RC_GIT

#define GIMP_MUTEX_VERSION "3"

#define GIMP_PACKAGE "gimp"

#define GIMP_PKGCONFIG_VERSION "3.0"

#define GIMP_PLUGIN_VERSION "3.0"

#define GIMP_RELEASE 1

#define GIMP_SYSCONF_VERSION "3.0"

#define GIMP_TOOL_VERSION "3.0"

#define GIMP_USER_VERSION "3.0"

#define GIMP_VERSION "3.0.4"

#define G_DISABLE_DEPRECATED

#define HAVE_ALLOCA 1

#undef HAVE_ALLOCA_H

#undef HAVE_ALSA

#define HAVE_BIND_TEXTDOMAIN_CODESET 1

#undef HAVE_DCGETTEXT

#define HAVE_DIFFTIME 1

#undef HAVE_DLFCN_H

#define HAVE_DX_DINPUT

#define HAVE_EXCHNDL

#undef HAVE_EXECINFO_H

#define HAVE_FCNTL_H 1

#undef HAVE_FSYNC

#define HAVE_FUNC_ATTRIBUTE_DESTRUCTOR

#undef HAVE_GETADDRINFO

#undef HAVE_GETNAMEINFO

#undef HAVE_GETTEXT

#define HAVE_IEEEFP_H 1

#define HAVE_INTTYPES_H 1

#undef HAVE_IPC_H

#define HAVE_ISO_CODES

#undef HAVE_LIBBACKTRACE

#undef HAVE_LIBGUDEV

#undef HAVE_LIBSOCKET

#undef HAVE_LIBUNWIND

#define HAVE_LOCALE_H 1

#define HAVE_MATH_H 1

#define HAVE_MEMORY_H 1

#undef HAVE_MMAN_H

#undef HAVE_MMAP

#define HAVE_OPENMP

#define HAVE_RINT 1

#undef HAVE_SHM_H

#define HAVE_STDINT_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_PARAM_H 1

#undef HAVE_SYS_PRCTL_H

#undef HAVE_SYS_SELECT_H

#define HAVE_SYS_STAT_H 1

#undef HAVE_SYS_THR_H

#undef HAVE_SYS_TIMES_H

#define HAVE_SYS_TIME_H 1

#define HAVE_SYS_TYPES_H 1

#undef HAVE_SYS_WAIT_H

#undef HAVE_THR_SELF

#define HAVE_UNISTD_H 1

#undef HAVE_VFORK

#define HAVE_VPRINTF 1

#undef HAVE_WEBKIT

#undef HAVE_X11_EXTENSIONS_SHAPE_H

#undef HAVE_X11_XMU_WINUTIL_H

#undef HAVE_XFIXES

#undef HAVE__NL_IDENTIFICATION_LANGUAGE

#undef HAVE__NL_MEASUREMENT_MEASUREMENT

#define INFODIR "share/info"

#define ISO_CODES_LOCALEDIR "share/locale"

#define ISO_CODES_LOCATION "share/xml/iso-codes"

#define LIBDIR "lib"

#define LIBEXECDIR "libexec"

#define LOCALEDIR "share/locale"

#define LOCALSTATEDIR "var"

#define MANDIR "share/man"

#define MYPAINT_BRUSHES_DIR "share/mypaint-data/1.0/brushes"

#undef NO_FD_SET

#define PACKAGE_BUGREPORT "https://gitlab.gnome.org/GNOME/gimp/issues/new"

#define PACKAGE_NAME "gimp"

#define PACKAGE_STRING "GIMP 3.0.4"

#undef PANGO_DISABLE_DEPRECATED

#define PLUGINDIR "lib/gimp/3.0"

#define PREFIX "C:/Users/Tiger/AppData/Local/Programs/GIMP 3"

#define SBINDIR "sbin"

#define SHAREDSTATEDIR "com"

#define SYSCONFDIR "etc"

#define SYSDATADIR "share"

#define USE_MMX

#define USE_SSE

#define WIN32_32BIT_DLL_FOLDER "32/bin"

